services:
  ### mysql ################################################
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'projector_l14'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3308:3308'
    expose:
      - '3308'
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./setup/mysql:/docker-entrypoint-initdb.d
      - ./data/logs:/var/log/mysql/
    networks:
      - p14

  ### nginx ################################################
  nginx:
    build:
      context: ./context/nginx
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - "${PWD}/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php-fpm
    networks:
      p14:
        ipv4_address: 172.16.240.20


  ### php-fpm ################################################
  php-fpm:
    build:
      context: ./context/php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - p14

  ### Grafana ################################################
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./data/grafana/provisioning/:/etc/grafana/provisioning/
      - ./data/grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    networks:
      - p14

  ### Telegraf ################################################
  telegraf:
    image: telegraf:1.21
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    ports:
      - '8125:8125/udp'
    networks:
      - p14

  ### InfluxDb ################################################
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - ./config/influxdb:/etc/influxdb2
      - ./data/influxdb:/var/lib/influxdb2
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
    networks:
      - p14

networks:
  p14:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.1